### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by nohtyp** [lusis/sensu_influxdb_handler#2]
I have this extension installed on my rhel 6 server sensu 0.12 with rvm 2.1, and 1.9.3 and the influxdb, timeout and the rubygems gems installed and when I restart the sensu-server I get the following in the logs, what am I doing wrong?

{"timestamp":"2014-05-22T00:34:00.654791-0400","level":"error","message":"failed to require extension","extension_file":"/etc/sensu/extensions/handlers/influx.rb","error":{"path":"influxdb","~mesg":"cannot load such file -- influxdb","~bt":["/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in`require'","/etc/sensu/extensions/handlers/influx.rb:3:in `<top (required)>'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in`require'","/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:31:in`block in require_directory'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:29:in `each'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/extensions.rb:29:in`require_directory'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/base.rb:59:in `extensions'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:24:in`initialize'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:13:in `new'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/lib/sensu/server.rb:13:in`run'","/opt/sensu/embedded/lib/ruby/gems/2.0.0/gems/sensu-0.12.6/bin/sensu-server:10:in `<top (required)>'","/opt/sensu/bin/sensu-server:23:in`load'","/opt/sensu/bin/sensu-server:23:in `<main>'"]}}
{"timestamp":"2014-05-22T00:34:00.655158-0400","level":"warn","message":"ignoring extension","extension_file":"/etc/sensu/extensions/handlers/influx.rb"}

**Comment by nohtyp** [comment]
I think i mighr have fixed my problem...

By adding your example (modified to my configs)
/etc/sensu/handlers/metrics/{influx.rb, metrics.json}
/etc/sensu/conf.d/influx.json

And restart of the sensu server i was able to see it load thw handler.  I will test it when i get to work and verify that i am recieving statistics in influxdb.

**Comment by nohtyp** [comment]
ok..It looks like I couldn't get this working..If you can please let me know what I am doing wrong...

based on your docs I was to put the influx.rb script in the extensions directory, but when I add it I get the above error.  When I add the file to /etc/sensu/handlers directory I can see the file loads but now my metrics are not being loaded into the database.

**Comment by nohtyp** [comment]
I created my own handler...Thanks anyway!

**Comment by cedric57** [comment]
you must use /opt/sensu/embedded/bin/gem in order to install influxdb gem

**Comment by yunsunghan** [comment]
thx for cedric57.
first,  /opt/~/fluent-gem install influxdb
second, /opt/~/fluent-gem install fluent-plugin-influxdb
it work!
